### ISSUE TITLE
error: e.Timeout.Milliseconds undefined

### ISSUE THREAD

**Issue by greenpau** [google/nftables#110]
When linking this library in `github.com/containernetworking/plugin` via vendors, I get the following error:

```
Building plugins 
  bandwidth
  firewall
# github.com/google/nftables/expr
vendor/github.com/google/nftables/expr/dynset.go:46:132: e.Timeout.Milliseconds undefined (type time.Duration has no field or method Milliseconds)
```

See also: https://github.com/containernetworking/plugins/issues/518#issuecomment-668250824

What is the best way of resolving this error?

**Comment by greenpau** [comment]
@stapelberg , is it really necessary to be milliseconds or it could be some division or multiplication? See also https://groups.google.com/forum/#!topic/golang-nuts/pret7hjDc70

**Comment by stapelberg** [comment]
You’re using a too old version of Go.

Milliseconds() was added in Go 1.13, with Go 1.14 being stable and Go 1.15 being around the corner.

The nftables package only supports the current stable version.

**Comment by greenpau** [comment]
> You’re using a too old version of Go.

@stapelberg , it is not me :-) It is https://github.com/containernetworking/plugins/blob/d713ec692c8d2da2bc567690846738a567d72f33/go.mod#L3

Thank you for the answer! I get it!
