### ISSUE TITLE
How to create SNPT

### ISSUE THREAD

**Issue by jack9603301** [google/nftables#116]
I used nftables to create a rule based on nat66:

```
table ip6 nat {
        chain PREROUTING {
                type nat hook prerouting priority dstnat; policy accept;
        }

        chain INPUT {
                type nat hook input priority 100; policy accept;
        }

        chain POSTROUTING {
                type nat hook postrouting priority srcnat; policy accept;
                counter packets 0 bytes 0 ip6 saddr fc00:2::/64 snat to 2001:5::/64 comment "NPT-NAT-1"
        }

        chain OUTPUT {
                type nat hook output priority -100; policy accept;
        }

        chain VYOS_DNPT_HOOK {
        }

        chain VYOS_SNPT_HOOK {
        }
}
```

The NAT66 rule seems to work normally, but it will change the interface identifier of the translated prefix, what should I do so that it does not change the interface identifier

**Comment by stapelberg** [comment]
I think you are in the wrong place.

As the README explains, this repository is a library for the Go programming language to interface with nftables.

If you have general nftables questions, you’ll need to ask them elsewhere. Sorry.
