### ISSUE TITLE
Adding a rule on position (index) 0

### ISSUE THREAD

**Issue by constcrist** [google/nftables#126]
I have not checked yet the netlink/netfilter code in the linux kernel for adding a new nf rule.
however, based on the `nft(8)`, "RULES" section, a `0` value for index is valid:
```
The add and insert commands support an optional location specifier, 
which is either a handle or the index (starting at zero) of an existing rule.
```
as far as I understand from the code, `Rule.Position` is basically the `index` documented in the `nft(8)` man page.
currently, the code in `rule.go` treats the `0` `Rule.Position` as "don't care" index:
```
    if r.Position != 0 {
        msgData = append(msgData, cc.marshalAttr([]netlink.Attribute{
            {Type: unix.NFTA_RULE_POSITION, Data: binaryutil.BigEndian.PutUint64(r.Position)},
        })...)
    }
```
is there any reason for this?
imo, if `0` is indeed a valid index, there should be a flag added to the `Rule` data structures which signals whether `Rule.Position` should be used or not.

**Comment by stapelberg** [comment]
cc @sbezverk 

> is there any reason for this?

Seems like an oversight to me

> imo, if `0` is indeed a valid index, there should be a flag added to the `Rule` data structures which signals whether `Rule.Position` should be used or not.

Agreed
