### ISSUE TITLE
Network byte order policy returned by `Conn.ListChains` is not converted to host byte order

### ISSUE THREAD

**Issue by constcrist** [google/nftables#130]
`chainFromMsg()` decodes the netlink message like this:
```
...
case unix.NFTA_CHAIN_POLICY:
  policy := ChainPolicy(ad.Uint32())
  c.Policy = &policy
...  
```

for example, for a chain configured on the system like this:

```
chain INPUT { # handle 2
   type nat hook input priority 100; policy accept;
}
```
 
`Conn.ListChains()` reports the policy value as `16777216`, or in hexadecimal `1000000`, whereas it should be `1`: 

```
// Possible ChainPolicy values.
const (
	ChainPolicyDrop ChainPolicy = iota
	ChainPolicyAccept
)
```

**Comment by stapelberg** [comment]
Thanks for the report. Can you send a PR to fix this please?

**Comment by constcrist** [comment]
hi @stapelberg ! I can but not right now. in a couple of days.
