### ISSUE TITLE
how to specify address mask with unspecified parent segments? (matching variable scope multicast addresses)

### ISSUE THREAD

**Issue by clandestinenetworks** [google/nftables#139]
I have two use cases for this that I recently came up with: 
- variable scope multicast addresses: https://www.iana.org/assignments/ipv6-multicast-addresses/ipv6-multicast-addresses.xhtml#variable there might be a CIDR mask here that I'm not seeing but I would still need to specify 255 * the number of CIDRs which is less than ideal 
- matching vanity IPv6 addresses, for example *any* addresses containing segments like `dead:beef:cafe`

is it possible to just specify the address? I can't test this at the moment but I'd like to do
something like this:
```
chain match_variable_scope { 
  # FF0X:0:0:0:0:0:0:FC
  ip6 saddr 0:0:0:0:0:0:0:FC accept
}
chain INPUT {
    type filter hook input priority 0; policy drop;                                                                                  
    ip6 saddr ff00::/8 jump match_variable_scope
}
```

but I'm guessing that would not work because:
```
::ffff:0:0/96,   # IPv4 mapped                                                                                                 
::ffff:0:0:0/96, # IPv4 translated           
```
will make it impossible to match `0000:0000:0000:0000:0000:ffff:ffff:ffff`

I suppose it might be possible to do actual bit masking (assuming the option is available) 
but I have no idea how to do that with nftables, but it seems like I saw an example somewhere of somebody trying to do something similar.

**Comment by stapelberg** [comment]
I think you are reporting an issue with nftables in the wrong place.

This is not the correct repository for issues with the Linux nftables project! This repository contains a third-party Go package to programmatically interact with nftables. Find the official nftables website at https://wiki.nftables.org/
