### ISSUE TITLE
include directive is flakey 

### ISSUE THREAD

**Issue by clandestinenetworks** [google/nftables#141]
- I wanted to specify multiple include files but only by canonical (fullpath) name but could not specify more than 1
- I have a number of sets that would be better stored in a separate file, however the include directive can only be specified outside of a table block and sets declared in a separate table block (regardless of the name of the table being the same) will not resolve.

**Comment by stapelberg** [comment]
I think you are reporting an issue with nftables in the wrong place.

This is not the correct repository for issues with the Linux nftables project! This repository contains a third-party Go package to programmatically interact with nftables. Find the official nftables website at https://wiki.nftables.org/
