### ISSUE TITLE
question about using glob pattern with iifname

### ISSUE THREAD

**Issue by clandestinenetworks** [google/nftables#142]
I read somewhere that it's faster to use `iif` and `oif` because they use the interface index instead of doing a string match on the interface. Presumably the person who prescribed this advice was implying that it would be string matching for each *packet* which surely is fine for any testing and diagnostic purposes but not ideal for production. 

I was just wondering if this was true or not. If it is true, I'm wondering why the parser would not just use the opportunity to glob match the interface when the rules are loaded and store it's index id instead of string matching for every packet; I understand also that part of the reason why this is nice to have is because it does not depend on the interface's existence to load the rule and that globs will match transient interfaces. In any case I suppose if it were to instead store the glob matched interface id that it would need to hook interface changed events and keep track of them 

It's really not that big of a deal either way, one way that I found to work around this is: 
```
set DEFAULT_INTERFACES_IN {                                                                                                        
    typeof iif                                                                                                                       
    flags interval                                                                                                                   
    # elements = { wlp114s0 }                                                                                                        
  }            
chain INTERFACES_IN {                                                                                                              
    iif @DEFAULT_INTERFACES_IN accept # skip slow matches if possible                                                                                           
    iifname "wlp*" accept                                                                                                            
    iifname "wlan*" accept                                                                                                           
    iifname "enp*" accept                                                                                                            
    iifname "eth*" accept                                                                                                            
    iifname "ens*" accept                                                                                                            
    iifname "tun*" accept                                                                                                            
    iifname "tap*" accept                                                                                                            
    iifname "VPN*" accept                                                                                                            
    limit rate 4 / day log prefix "!DEFAULTIFIN: "                                                                                   
    return comment "make sure to always return from this chain if not matched"                                                       
  }                                     
```

**Comment by stapelberg** [comment]
I think you are reporting an issue with nftables in the wrong place.

This is not the correct repository for issues with the Linux nftables project! This repository contains a third-party Go package to programmatically interact with nftables. Find the official nftables website at https://wiki.nftables.org/
