### ISSUE TITLE
Riscv64 support

### ISSUE THREAD

**Issue by kirana1996** [google/nftables#148]
Hi,
       I trying to build nftable with json support on riscv64 target but facing bellow xsltproc error. Can help us resolve this  issue.
         
 make[2]: Entering directory '/home/root/kiran/nftables/doc'
GEN nft.8
a2x: ERROR: xsltproc --nonet --stringparam callout.graphics 0 --stringparam navig.graphics 0 --stringparam admon.textlabel 1 --stringparam admon.graphics 0 "/etc/asciidoc/docbook-xsl/manpage.xsl" "/home/root/kiran/nftables/doc/nft.xml" returned non-zero exit status 5

make[2]: *** [Makefile:638: nft.8] Error 1
make[2]: Leaving directory '/home/root/kiran/nftables/doc'
make[1]: *** [Makefile:478: all-recursive] Error 1
make[1]: Leaving directory '/home/root/kiran/nftables'
make: *** [Makefile:387: all] Error 2

Reproduced Steps:
     $ git clone https://github.com/google/nftables.git
     $ cd nftables 
     $ ./autogen.sh
     $ ./configure --with-json
     $ make

Thanks,

``

**Comment by stapelberg** [comment]
I think you are reporting an issue with nftables in the wrong place.

This is not the correct repository for issues with the Linux nftables project! This repository contains a third-party Go package to programmatically interact with nftables. Find the official nftables website at https://wiki.nftables.org/
