### ISSUE TITLE
Unsupported (data) expressions "target" and "match"

### ISSUE THREAD

**Issue by thediveo** [google/nftables#161]
When getting the rules of all chains of all tables in the host of an Ubuntu 21.10 system I notice missing expressions. For testing, I've made the currently "silent" `exprsFromMsg` function to dump the names of currently unimplemented `NFTA_EXPR_DATA` names. This shows `target` and `match` data expressions.

Would you like a PR for these two types?

A few questions about un/marshalling strings which are per netfilter source `char[fixelen]`, such as the `name` attribute in a  target data structure:
1. should the Go type stick with `string` instead of a fixed-size array?
2. would unmarshalling `string(bytes.Trim(ad.Bytes(), "\x00"))` be the correct way instead of `ad.String()`?

**Comment by stapelberg** [comment]
> Would you like a PR for these two types?

Sure!

> A few questions about un/marshalling strings which are per netfilter source `char[fixelen]`, such as the `name` attribute in a target data structure:

Can you send a link to the definition please?

> * should the Go type stick with `string` instead of a fixed-size array?

Probably string + length check would be the best way. That way, should the fixed size array ever grow larger in the kernel, we can easily adapt without breaking anyone.

> * would unmarshalling `string(bytes.Trim(ad.Bytes(), "\x00"))` be the correct way instead of `ad.String()`?

expr/verdict.go uses a similar approach: https://github.com/google/nftables/blob/eeaebcf552951a01af8c359bec279367468aca28/expr/verdict.go#L118

**Comment by thediveo** [comment]
> > A few questions about un/marshalling strings which are per netfilter source `char[fixelen]`, such as the `name` attribute in a target data structure:
> 
> Can you send a link to the definition please?

I've included the asked information in PR #163, so we can discuss on the code itself.

**Comment by thediveo** [comment]
Done.
