### ISSUE TITLE
Rules not block RAW data

### ISSUE THREAD

**Issue by y-shevchenko** [google/nftables#167]
```nft add rule ip filter INPUT @th,64,88 0x64313A6164323A69643230 counter drop```
This rule does not block traffic, according to the counter the rule works but does not block

**Comment by stapelberg** [comment]
I think you are reporting an issue with nftables in the wrong place.

This is not the correct repository for issues with the Linux nftables project! This repository contains a third-party Go package to programmatically interact with nftables. Find the official nftables website at https://wiki.nftables.org/
