### ISSUE TITLE
Is dynamic set or meters supported?

### ISSUE THREAD

**Issue by zjuchenchao** [google/nftables#172]
I find keyword meters [here](https://wiki.nftables.org/wiki-nftables/index.php/Meters), and I'd like to limit rate per second like this

```
nft add rule ip filter INPUT meter myMeter { ip saddr limit rate 200/second } counter drop --debug=netlink
myMeter filter 21
myMeter filter 0
ip filter INPUT 
  [ payload load 4b @ network header + 12 => reg 1 ]
  [ dynset add reg_key 1 set myMeter expr [ limit rate 200/second burst 0 type packets flags 0x0 ] ]
  [ counter pkts 0 bytes 0 ]
  [ immediate reg 0 drop ]
```
The 2nd expr should be a dynset, but how can I add the _expr [ limit rate 200/second burst 0 type packets flags 0x0 ]_ to the dynset?
https://pkg.go.dev/github.com/google/nftables#Set
https://pkg.go.dev/github.com/google/nftables/expr#Dynset
https://pkg.go.dev/github.com/google/nftables/expr#Limit
I looked it up on go.dev. Maybe I should add the limit expr to a set, and add SetID and SetName to the dynset, but SetDatatype cannot be a expr. Is there a way to make it or am I thinking wrong? Thanks a lot.

**Comment by stapelberg** [comment]
Our expr.Dynset implementation does not currently support expressions. See the upstream libnftnl code for confirmation: https://sources.debian.org/src/libnftnl/1.2.2-1/src/expr/dynset.c/?hl=167#L167 — that code marshals `NFTA_DYNSET_EXPR` (single expression) or `NFTA_DYNSET_EXPRESSIONS` (multiple expressions) in addition to the attributes that we already have.

Feel free to send a PR to add expression support to expr.Dynset.

**Comment by Furisto** [comment]
What about support for meters? I am trying to implement this
`nft add rule ip filter output ip protocol tcp ct state new meter ratemeter '{ ip daddr & 0.0.0.0 timeout 1m limit rate over 10/minute }' counter drop`

but do  not see any way to express that. Any pointers?

**Comment by stapelberg** [comment]
> nft add rule ip filter output ip protocol tcp ct state new meter ratemeter '{ ip daddr & 0.0.0.0 timeout 1m limit rate over 10/minute }' counter drop

By adding `--debug=all`, we can see:

```
% nft --debug=all add rule ip filter output ip protocol tcp ct state new meter ratemeter '{ ip daddr & 0.0.0.0 timeout 1m limit rate over 10/minute }' counter drop
[…]
ip filter output
  [ payload load 1b @ network header + 9 => reg 1 ]
  [ cmp eq reg 1 0x00000006 ]
  [ ct load state => reg 1 ]
  [ bitwise reg 1 = ( reg 1 & 0x00000008 ) ^ 0x00000000 ]
  [ cmp neq reg 1 0x00000000 ]
  [ payload load 4b @ network header + 16 => reg 1 ]
  [ bitwise reg 1 = ( reg 1 & 0x00000000 ) ^ 0x00000000 ]
  [ dynset update reg_key 1 set ratemeter timeout 60000ms expr [ limit rate 10/minute burst 5 type packets flags 0x1 ] ]
  [ counter pkts 0 bytes 0 ]
  [ immediate reg 0 drop ]
```

Looks like the meter is implemented as dynset expressions, too.

**Comment by zjuchenchao** [comment]
Yes, as[ the instruction in the wiki](https://wiki.nftables.org/wiki-nftables/index.php/Meters), `Dynamic sets/maps or meters are a way to use maps with stateful objects. ` I believe dynamic sets are equal to meters.
Sorry to say I'm new to nft, but I will continue to monitor it
