### ISSUE TITLE
Feature request: ability to create chains without Hook or Priority

### ISSUE THREAD

**Issue by capnspacehook** [google/nftables#179]
I'm trying to use this library to filter Docker container traffic, to do that I have to jump from the `iptables` created `DOCKER-USER` chain to a nftables chain that I ideally create. Currently it is not possible to create a nftables chain without `Hooknum` or `Priority` set, when those fields are set upon chain creation, `iptables` and `nft` alike do not allow jumping between chains. 

I have 2 different ideas for implementation: 
1. Add an additional field to the `Chain` struct such as `Legacy` that signals `Hooknum` and `Priority` must be ignored when creating the chain. This is very easy to implement and doesn't break backwards compatibility, but might not be very clear to use.
2. Make the `Hooknum` and `Priority` fields pointers like `Policy`. This is the easiest to understand from an API perspective, but will break backwards compatibility and require fixing a lot of tests. 

I know this module is in a pre-v1.0.0 state where maintaining backwards compatibility isn't a huge concern, but it's worth noting nonetheless.

**Comment by stapelberg** [comment]
Thanks for filing this issue, I didn’t know that for some chains these fields must not be set.

I think there is a way that we can change the fields to a pointer and keep existing code working: by converting constants like `ChainTypeFilter` to global pointer variables.

Can you give that a shot and send a PR if it works?

Thanks
