### ISSUE TITLE
jump to  a chain

### ISSUE THREAD

**Issue by sbezverk** [google/nftables#18]
nft rule to jump to a different chain requires immediate expression to provide two parameters, 1 is jump command and 2 is the name of chain. Currently it does not seem to be supported.

```
sbezverk@ubuntu:~$ sudo nft --debug all add rule istio istio_outbound tcp dport 1-65535 jump istio_redirect
```

**Comment by sbezverk** [comment]
@stapelberg as per your request, here is a new issue submitted to address `jump` functionality.

**Comment by sbezverk** [comment]
@stapelberg another verdict needed is return:
`nft --debug all add rule istio istio_outbound meta skgid 1337 return`
```
| 69 6d 6d 65  |	|      data      |	 i m m e
| 64 69 61 74  |	|      data      |	 d i a t
| 65 00 00 00  |	|      data      |	 e      
|00028|N-|00002|	|len |flags| type|
|00008|--|00001|	|len |flags| type|
| 00 00 00 00  |	|      data      |	        
|00016|N-|00002|	|len |flags| type|
|00012|N-|00002|	|len |flags| type|
|00008|--|00001|	|len |flags| type|
| ff ff ff fb  |	|      data      |	        
----------------	------------------
```
it could be done with converting -5 into a byte slice but would be nice to have proper interface.

**Comment by stapelberg** [comment]
Ah, you’re about to use this package in istio? Can you provide more details about what you’re doing? Just curious :) 

Will take a look at this in a bit.

**Comment by stapelberg** [comment]
Both fixed now.

**Comment by sbezverk** [comment]
@stapelberg thanks for quick fix!! Currently Istio uses iptables in init container. I would like to start first with swapping itables in istio-cni and if it all goes well, I will propose the same change for istio. There are a few things which might be problematic. I will have to make sure ipv6 is supported. Also you do not expose interface in nftables which make a little difficult to do mock. I am building a library with higher level func which will import and use in istio-cni.
