### ISSUE TITLE
range support

### ISSUE THREAD

**Issue by sbezverk** [google/nftables#19]
Appreciate if you could add support for `range`
add rule ip filter-v4 chain-1-v4 tcp sport != 2024-2030 return
                                                        
  [ meta load l4proto => reg 1 ]
  [ cmp eq reg 1 0x00000006 ]
  [ payload load 2b @ transport header + 0 => reg 1 ]
  [ range neq reg 1 0x0000e807 0x0000ee07 ]
  [ immediate reg 0 return ]

**Comment by stapelberg** [comment]
Do you want to give this a shot yourself? You’ve seen a few of my commits :)

**Comment by sbezverk** [comment]
@stapelberg sure thing, let me give it a shot.
