### ISSUE TITLE
Consider using netlink.AttributeDecoder

### ISSUE THREAD

**Issue by mdlayher** [google/nftables#2]
Hey hey. Not really an issue, per say, but I recently decided to rethink how I was decoding netlink attributes and ended up coming up with:

https://godoc.org/github.com/mdlayher/netlink#AttributeDecoder

See the example there for some usage too. It's a bit safer than the typical memory casts I'd been doing before with nlenc directly. Perhaps it'll be useful here too.

I don't have a better encoding solution yet but perhaps that will come as well as I continue working on wireguardctrl!

**Comment by stapelberg** [comment]
I gave this a shot, but hit an issue: https://godoc.org/github.com/mdlayher/netlink#AttributeDecoder.Uint32 seems to decode an uint32 using the host’s endianness: https://github.com/mdlayher/netlink/blob/3d8cc9af89458b8b6a9ce675d4dfa50a724e9025/nlenc/int.go#L78

For nftables, however, values are stored in big endian most of the time, only the resource id in the extraHeader field is stored in native endian.

A specific place where this causes issues is: https://github.com/google/nftables/blob/121db0bb236f1414c97c487e39ee51fbc4fa4fcc/nftables.go#L519

With the current code, objectType will be set to 1, but when using `ad.Uint32()`, it gets set to 16777216.

**Comment by mdlayher** [comment]
Interesting! Every netlink family I've worked with has used native endianness for attributes so far. I suppose it wouldn't hurt for me to add an option to set the endianness on the decoder!

**Comment by stapelberg** [comment]
From what I can tell, it’s all big endian for nftables.

Let me know what decision you end up with, and I can give this another shot.

**Comment by mdlayher** [comment]
I've added a new tunable as of https://github.com/mdlayher/netlink/commit/ff3050a9954d550573f84188d9a7566ca313b6ae: https://godoc.org/github.com/mdlayher/netlink#AttributeDecoder.

I considered adding it to the constructor as well, but figured it'd be cleaner to allow overriding the default after construction.  Let me know what you think.

**Comment by stapelberg** [comment]
Yeah, this worked. Are you planning to add an AttributeEncoder, too? :)

**Comment by mdlayher** [comment]
Yeah; starting to think about that problem as well due to the situations I've gotten myself into with: https://github.com/mdlayher/wireguardctrl/blob/master/internal/wgnl/configure_linux.go and its tests.  I imagine I'll do something reasonably similar.
