### ISSUE TITLE
Please consider create a release/tag

### ISSUE THREAD

**Issue by CyrilBrulebois** [google/nftables#208]
Hi,

I'm in the process of packaging [CrowdSec](https://www.crowdsec.net/) and some of its bouncers for the Debian distribution. The firewall one depends on your package, and it would be great if I could package an official release/tag instead of a snapshot, which would give a slightly ugly version number (e.g. `0.0~git20221107.130caa4`).

Thanks for considering!

Cheers, 
Cyril.

**Comment by stapelberg** [comment]
Hey Cyril! I just published a v0.1.0 tag. Hope this helps
