### ISSUE TITLE
Alignment issues on 32-bit archs: TestAlignedBuff32 & TestAlignedBuffInt32 failures

### ISSUE THREAD

**Issue by CyrilBrulebois** [google/nftables#209]
Hi,

Seen on armel, armhf, and i386 via autopkgtest on the https://ci.debian.net/ infrastructure, i.e. all 32-bit architectures:

```
=== RUN   TestAlignedBuff32
    alignedbuff_test.go:107: alignment padding failed: 12
--- FAIL: TestAlignedBuff32 (0.00s)
```

and:

```
=== RUN   TestAlignedBuffInt32
    alignedbuff_test.go:218: alignment padding failed: 12
--- FAIL: TestAlignedBuffInt32 (0.00s)
```

(I've added the actual length by adjusting the source, 16 is expected in both places.)

I'm happy to try anything you'd like me to; this issue can be easily reproduced locally by building the `golang-github-google-nftables` package within an i386 development chroot (Debian unstable), e.g. on an amd64 system.

**Comment by stapelberg** [comment]
cc @thediveo who contributed alignedbuff

**Comment by thediveo** [comment]
I suspect my test to be (obviously) incorrectly done, I need to test the test next time. Somehow the 32bit archs return to exact revenge on me. Unfortunately, I need to setup a test VM or similar first.

**Comment by CyrilBrulebois** [comment]
If you want to push a branch, commits, patches, etc. somewhere, I'm happy to run tests and report back if that lowers the barrier for you.

**Comment by thediveo** [comment]
thank you very much! but I need to first explore this, as Go behaves differently from the C compilers in some aspects of 64bit versus 32bit architectures. nftables need to use the C alignment rules...

**Comment by thediveo** [comment]
I've now set up a Debian 11 i386 VM on kvm/qemu ... the only bummer is that there's no 32bit versions of VSCode anymore. I can reproduce using go version 1.19.4 on linux/386.

**Comment by CyrilBrulebois** [comment]
With your commit, it builds and tests fine at least on amd64 and i386 indeed, thanks! Would like me to run some tests on arm* systems (I have access to a few porter boxes via my Debian hat, including armel and armhf).

**Comment by thediveo** [comment]
yes, please, if that is possible.

**Comment by CyrilBrulebois** [comment]
Confirmed building and testing fine with 318b4afcdd40d17a3dd2f583e79586373be1626d on armel and armhf, in addition to amd64 and i386.
