### ISSUE TITLE
List chains?

### ISSUE THREAD

**Issue by jniewt** [google/nftables#21]
Is there a way to list all existing chains for a table with this library?

**Comment by stapelberg** [comment]
Not yet :)

Would you like to contribute this feature? For inspiration, you can take a look at https://github.com/google/nftables/blob/8cccfeed7c0b7e23de98a7039a0ac8b6ab86abac/table.go#L78

**Comment by jniewt** [comment]
I will take a look but I don't think I'm up to it.

**Comment by stapelberg** [comment]
Cool. Let me know where you get stuck and I might be able to provide a pointer.

**Comment by stapelberg** [comment]
fixed with PR #25
