### ISSUE TITLE
Reason for not wrapping libnftnl/libmnl.

### ISSUE THREAD

**Issue by C0llect0r** [google/nftables#212]
Hey folks,

i just wanted to know what your reasons were not to wrap around libnftnl/libmnl.
I'm currently considering this repository for a project, but the fact that it is not directly maintained by netfilter and any changes to the underlying structure of nftables could potentially break things on a deeper level (and potentially much longer) in this version is a bit of a bummer.

Any arguments for using this library and not wrapping libnftnl/libmnl myself are heavily appreciated :smile: .

**Comment by stapelberg** [comment]
libnftnl/libmnl are C libraries, and this `nftables` package must not depend on any C code.

I’m using it as part of https://router7.org/, which is built on https://gokrazy.org/, where there is no C userland (only Linux + Go).

I don’t think kernel folks are likely to break compatibility, though. Keep in mind that new kernel versions are usually expected to work with older userland versions.
