### ISSUE TITLE
nftables go dynset implementation will not work with libnftnl versions <1.1.9

### ISSUE THREAD

**Issue by turekt** [google/nftables#215]
Hi,

I have noticed that go nftables lib tests are failing on older versions of nftables (or more precisely Debian):
```
# go test -run_system_tests ./...
--- FAIL: TestDynsetWithOneExpression (0.03s)
    nftables_test.go:3912: c.Flush() failed: conn.Receive: netlink receive: operation not supported
    nftables_test.go:3921: unexpected number of rules: got 0, want 1
--- FAIL: TestDynsetWithMultipleExpressions (0.04s)
    nftables_test.go:4018: c.Flush() failed: conn.Receive: netlink receive: operation not supported
    nftables_test.go:4027: unexpected number of rules: got 0, want 1
FAIL
exit status 1
FAIL	github.com/google/nftables	1.211s
# nft --version
nftables v0.9.8 (E.D.S.)
```

Everything seems to be fine when running tests on latest nftables/Debian: 
```
# go test -run_system_tests ./...
PASS
ok  	github.com/google/nftables	1.263s
# nft --version
nftables v1.0.2 (Lester Gooch)
```

I have traced the issue being caused by NFT_DYNSET_F_EXPR flag set here: 
https://github.com/google/nftables/blob/9aa6fdf5a28cdfec5695ebbf7d7add61eccdf61a/expr/dynset.go#L68

The libnftnl package listed on https://sources.debian.org/src/libnftnl/ show the following versions:
```
version[ 1.2.4-2](https://sources.debian.org/src/libnftnl/1.2.4-2/) (main) [bookworm, sid]
version[ 1.1.9-1](https://sources.debian.org/src/libnftnl/1.1.9-1/) (main) [bullseye]
version[ 1.1.7-1~bpo10+1](https://sources.debian.org/src/libnftnl/1.1.7-1~bpo10%2B1/) (main) [buster-backports]
version[ 1.1.2-2](https://sources.debian.org/src/libnftnl/1.1.2-2/) (main) [buster]
version[ 1.1.1-1~bpo9+1](https://sources.debian.org/src/libnftnl/1.1.1-1~bpo9%2B1/) (main) [stretch-backports]
version[ 1.0.7-1](https://sources.debian.org/src/libnftnl/1.0.7-1/) (main) [stretch]
version[ 1.0.7-1~bpo8+1](https://sources.debian.org/src/libnftnl/1.0.7-1~bpo8%2B1/) (main) [jessie-backports]
```

The libnftnl 1.1.9 release commit is here:
https://git.netfilter.org/libnftnl/commit/?id=c3fdda6ac8675aea9b35772458544f03157be415

Parent commit to the release commit, NFTNL_EXPR_DYNSET_FLAGS is introduced: https://git.netfilter.org/libnftnl/commit/?id=20503ffb5cbbe75e03b34f0386d24badfd9cb299 and parent commit prior to DYNSET_FLAGS, our NFTNL_EXPR_DYNSET_EXPRESSIONS is introduced: https://git.netfilter.org/libnftnl/commit/?id=373445dc54eda77fc7b64fddf5e7d35536df51b0

Therefore, the root cause for this issue lies in the libnftnl library which did not implement NFTA_DYNSET_EXPRESSIONS until version 1.1.9 and that is why I was able to reproduce the failed test case(s) on earlier versions of Debian.

Nevertheless, single expressions were supported by dynsets prior to version 1.1.9. This means that go nftables lib currently supports only libnftnl version 1.1.9 and up, but cannot support earlier versions and single dynset expressions due to NFT_DYNSET_F_EXPR being set for both single and multiple dynset expressions. On the older version of libnftnl, the single expression test case succeeds when I remove the NFT_DYNSET_F_EXPR flag as seen here 
https://github.com/google/nftables/blob/9aa6fdf5a28cdfec5695ebbf7d7add61eccdf61a/expr/dynset.go#L68 (the multiple expression still fails for me since this is not a supported feature).

Do you think that it makes sense to adapt `expr/dynset.go` to support earlier versions of libnftnl? This could be done with an additional flag set by the user which would indicate whether NFT_DYNSET_F_EXPR flag needs to be set or not. Unfortunately, I am not sure if there is a way for the lib to recognize whether NFTA_DYNSET_EXPRESSIONS is supported or not without the user specifying this information.

Let me know what you think.

**Comment by stapelberg** [comment]
Thanks for your analysis!

Debian bullseye (current stable) was released in August 2021, and release preparation for the next stable version are about to start in just a few weeks.

If I understand correctly, dynsets created with this nftables package only work on Debian bullseye and newer. I think that’s acceptable. If anyone has a specific need for more compatibility, they can let us know and we can reconsider.
