### ISSUE TITLE
Feature: add support for monitor

### ISSUE THREAD

**Issue by singchia** [google/nftables#224]
It seems this library doesn't support MONITOR, which allows to listen to netlink events like creation and deletion of objects.

For example: 

`nft monitor chains` to monitor changes on chains.

If so, I would like to submit a PR to support this.

**Comment by singchia** [comment]
OK, working on it.

**Comment by cheina97** [comment]
This feature is still a work in progress?

**Comment by singchia** [comment]
Yes, new PR will be submitted recently.

**Comment by cheina97** [comment]
Thanks @singchia ❤️

**Comment by singchia** [comment]
the PR is here #250 
 hope we can make it faster to be merged.
