### ISSUE TITLE
Broken deps

### ISSUE THREAD

**Issue by purpleidea** [google/nftables#254]
Nice project, this is exactly what I was looking for. In particular the `monitor` support. I want those events for https://github.com/purpleidea/mgmt/

I noticed the latest release doesn't have those in, and also that it doesn't seem to build. For example:

```
$ go get github.com/google/nftables
go: downloading honnef.co/go/tools v0.2.2
go: downloading github.com/BurntSushi/toml v0.4.1
go: upgraded github.com/BurntSushi/toml v0.3.1 => v0.4.1
go: added github.com/google/nftables v0.1.0
go: upgraded github.com/mdlayher/netlink v1.1.1 => v1.4.2
go: upgraded honnef.co/go/tools v0.0.1-2020.1.4 => v0.2.2
$ make # my software
# github.com/mdlayher/netlink
../gopath/pkg/mod/github.com/mdlayher/netlink@v1.4.2/conn_linux.go:61:66: not enough arguments in call to socket.Socket
	have (number, number, int, string)
	want (int, int, int, string, *socket.Config)

make: *** [Makefile: build] Error 1
```

But if I chose main:

```
$ go get github.com/google/nftables@main
go: downloading github.com/google/nftables v0.1.1-0.20240112203004-33ee8df9d8e2
go: upgraded github.com/google/nftables v0.1.0 => v0.1.1-0.20240112203004-33ee8df9d8e2
go: upgraded github.com/mdlayher/netlink v1.4.2 => v1.7.1
go: upgraded github.com/mdlayher/socket v0.2.3 => v0.4.0
```

Things work great! This is really golang's fault for making it difficult to follow the main/master branch, but I digress.

You may wish to release a new version if that's helpful. At the least, the godocs would get updated since they don't show the `monitor` stuff and I only found it when digging through the source.

Lastly, you might want to add `context.Context` to close the watch, instead of the `Close` method, but that's up to you.

Thanks again!

Cheers!

**Comment by stapelberg** [comment]
Thanks for the hint, I updated the dependencies and tagged a new version.

For the Context change, please send a PR.

**Comment by purpleidea** [comment]
> For the Context change, please send a PR.

I'd love to, however I can't sign your CLA sorry. If you can exempt me from that or disable it, please let me know, this issue would have been a patch too! =D

**Comment by stapelberg** [comment]
I cannot, sorry. Corporate policies.
