### ISSUE TITLE
nftables ip6 postrouting and prerouting issue

### ISSUE THREAD

**Issue by xiv3r** [google/nftables#281]
nft add chain ip6 filter prerouting { type filter hook prerouting priority 0; }
nft add rule ip6 filter prerouting ip6 hl 1 set hl 65

Syntax error, Unexpected string

**Comment by stapelberg** [comment]
You’re in the wrong place:

This is not the correct repository for issues with the Linux nftables project! This repository contains a third-party Go package to programmatically interact with nftables. Find the official nftables website at https://wiki.nftables.org/
