### ISSUE TITLE
Comment for set

### ISSUE THREAD

**Issue by sanya2022** [google/nftables#288]
When using the nft utility, you can create a set with a comment:
`nft add set inet tablename setname { type ipv4_addr\; comment \"test comment\" \; }`

Is it possible to set comment for Set using this library? I didn't find Comment in set type.

Thanks a lot.

**Comment by turekt** [comment]
Hi @sanya2022, adding a comment to a set directly is currently not supported. There is an existing implementation of userdata TLV so its a fairly small change in order to support it. I have opened PR #290 which should resolve this for you.

```sh
# cat main.go
package main

import (
	"github.com/google/nftables"
)

func main() {
	c, err := nftables.New()
	if err != nil {
		panic(err)
	}

	c.FlushRuleset()

	filter := c.AddTable(&nftables.Table{
		Family: nftables.TableFamilyINet,
		Name:   "filter",
	})

	if err := c.AddSet(&nftables.Set{
		Table:   filter,
		Name:    "setname",
		KeyType: nftables.TypeIPAddr,
		Comment: "test comment",
	}, nil); err != nil {
		panic(err)
	}

	if err := c.Flush(); err != nil {
		panic(err)
	}
}
# nft flush ruleset
# go run main.go
# nft list ruleset
table inet filter {
	set setname {
		type ipv4_addr
		comment "test comment"
	}
}
```

**Comment by sanya2022** [comment]
Thanks a lot!
