### ISSUE TITLE
Implement hash module

### ISSUE THREAD

**Issue by Minaru** [google/nftables#62]
The goal would be to be able to use the internal hashing capabilities of nftables through a new kind of `expr` ([Hashing section](https://wiki.nftables.org/wiki-nftables/index.php/Math_operations)).

I already found all the hashing related unix constants, need to figure out what each of those keys expect as attributes before implementing that in the golang nftables module.

```
NFT_HASH_JENKINS                  = 0x0
NFT_HASH_SYM                      = 0x1
NFTA_HASH_UNSPEC                  = 0x0
NFTA_HASH_SREG                    = 0x1
NFTA_HASH_DREG                    = 0x2
NFTA_HASH_LEN                     = 0x3
NFTA_HASH_MODULUS                 = 0x4
NFTA_HASH_SEED                    = 0x5
NFTA_HASH_OFFSET                  = 0x6
NFTA_HASH_TYPE                    = 0x7
```

I can take care of that PR as well, but I'll probably need some guidance/feedback/correction on the code I'll produce as it'll be my first time contributing on a big part of the project.

**Comment by stapelberg** [comment]
> I can take care of that PR as well, but I'll probably need some guidance/feedback/correction on the code I'll produce as it'll be my first time contributing on a big part of the project.

Sure thing! Thanks in advance

**Comment by Minaru** [comment]
Branch with the `hash` `expr` can be found [here](https://github.com/Minaru/nftables/blob/hash_implem/expr/hash.go)

After trying it locally, it seems to insert what I expect it to insert given the data I provide it. However I have a slight doubt about the `LEN` parameter. Considering we don't have to explicitly write it through CLI, do we have to make sure in the code that it's not equal to 0 ?

I know the good approach to code any rule with this package is to add manually the rule with `debug all` option, then see what it does (like the code snipet code under this paragraph), then translate it with the proper `expr` array (other code snipet). It works that way, and netlink just send you back an error if you leave `LEN` to 0 anyway. I'd go for the no-check method myself as the dev has all the data they need to provide that parameter, that replacing `LEN` by an arbitrary value when equal to 0 would just be a huge headache for anyone new to this when debugging, and also that netlink already throws an error (`panic: Receive: netlink receive: numerical result out of range`) when given a `LEN` equals to 0. Just want to be sure that is the proper approach before making the PR.

Hash rule that takes source ip and dest ip as a base, and 0xfeedcafe as seed, mod 100 offset 1 (len 8 is automatically computed by nftables):
```
  [ ct load state => reg 1 ]
  [ bitwise reg 1 = (reg=1 & 0x00000008 ) ^ 0x00000000 ]
  [ cmp neq reg 1 0x00000000 ]
  [ payload load 4b @ network header + 12 => reg 2 ]
  [ payload load 4b @ network header + 16 => reg 13 ]
  [ hash reg 1 = jhash(reg 2, 8, 0xfeedcafe) % mod 100 offset 1 ]
  [ meta set mark with reg 1 ]
  [ meta load mark => reg 1 ]
  [ ct set mark with reg 1 ]
  [ immediate reg 0 accept ]
```
Resulting Hash expr for the rule above:
```
&expr.Hash{
    DestRegister: 1,
    SourceRegister: 2,
    Length: 8,
    Modulus: 100,
    Seed: 4276996862,
    Offset: 1,
    Type: expr.HashTypeJenkins,
}
```

**Comment by Minaru** [comment]
From what I've seen, the nft userspace CLI automatically computes the LEN parameter given the mod/offset parameters (so all possible hash result can be contained in the var of LEN size).

I wrote a test case in the PR I'll make just after finishing that comment, where the given LEN is 4. The proper approach seems to be the no-check one. Netlink will yell at the dev in case LEN is initialized anyway.

**Comment by Minaru** [comment]
Closing this as this is merged.
