### ISSUE TITLE
Stateless NAT and packet duplication

### ISSUE THREAD

**Issue by alexispires** [google/nftables#80]
Hi,

Is there any way to use packet duplication and stateless nat?

- https://wiki.nftables.org/wiki-nftables/index.php/Duplicating_packets
- https://wiki.nftables.org/wiki-nftables/index.php/Performing_Network_Address_Translation_(NAT)#Stateless_NAT

Tx !

**Comment by stapelberg** [comment]
You’re posting this in the wrong place. The google/nftables repository is a Go package to programmatically interact with nftables, not affiliated with the nftables developers itself in any way.

**Comment by alexispires** [comment]
I misspoke. Is there any way to use packet duplication and stateless nat **with this package**?

**Comment by stapelberg** [comment]
If that’s something you can express with nftables per se, you should be able to express it with this package, too. Not all expressions are implemented, though, so you might need to add a bit of code.

If you provide the nft commands to configure the setup you have in mind, I can give you a few more specific pointers.

**Comment by alexispires** [comment]
Something like this:
```
nft add rule ip filter prerouting ip protocol udp ip daddr set 172.19.0.2 dup to 172.19.0.6 notrack
```

**Comment by stapelberg** [comment]
So, adding `--debug=all` to your command yields:

```
ip filter prerouting 
  [ payload load 1b @ network header + 9 => reg 1 ]
  [ cmp eq reg 1 0x00000011 ]
  [ immediate reg 1 0x020013ac ]
  [ payload write reg 1 => 4b @ network header + 16 csum_type 1 csum_off 10 csum_flags 0x1 ]
  [ immediate reg 1 0x060013ac ]
  [ dup sreg_addr 1 ]
  [ notrack ]
```

Going through the fields one by one:

* expr.Payload exists
* expr.Cmp exists
* expr.Immediate exists
* expr.Payload exists, but you’d need to add a few fields for the csum-related parameters
* expr.Immediate exists
* expr.Dup does not exist yet
* expr.Notrack does not exist yet

Have a look at the commit history to see how to add new expressions.

Hope that helps,
