### ISSUE TITLE
Weird behaviors of Obj API

### ISSUE THREAD

**Issue by alexispires** [google/nftables#90]
Hello,

I noticed weird behaviors of Obj API with counters (perhaps with other objects too): 
- GetObj(Obj) : return all counters, not only the given one
- GetObjReset(Obj) : reset all counters, not only the given one

Tests are not robust and can't tell me if it's the wanted behaviors.

The consequence of that:
- No clean API to retrieve all counters
- No API to retrieve values of a given counter
- No API to reset a given counter

@stapelberg @sbezverk

**Comment by stapelberg** [comment]
In https://github.com/rtr7/router7, I only have one counter per address family, so I never noticed.

I think the API should be changed to only return the object with the name, if a name is specified. Leaving the name empty could be the way to obtain all counters. That should address all issues raised, I think?

**Comment by sbezverk** [comment]
I suspect by manipulating these attributes an individual object can be retrieved.
```
    NFTA_OBJ_TABLE                    = 0x1
    NFTA_OBJ_NAME                     = 0x2
    NFTA_OBJ_TYPE                     = 0x3
    NFTA_OBJ_DATA                     = 0x4
    NFTA_OBJ_USE                      = 0x5
```
But I have not played with these yet.

**Comment by alexispires** [comment]
It seems it's because of NLM_F_DUMP flag. By removing it, it's works.
I'll try something

**Comment by alexispires** [comment]
> In https://github.com/rtr7/router7, I only have one counter per address family, so I never noticed.
> 
> I think the API should be changed to only return the object with the name, if a name is specified. Leaving the name empty could be the way to obtain all counters. That should address all issues raised, I think?

@stapelberg 

My proposition:
GetObj(o Obj) (Obj, error)
GetObjs(t Table) ([]Obj, error)
ResetObj(o Obj) (Obj, error)
ResetObjs(t Table) ([]Obj, error)

My concern is that it's not consistent with Rule API. GetRule return all rules in the given table and GetObj just the given Obj from kernel. Maybe consider to name it GetSingleObj(), i don't know..
